version: "3"

services:
  ai-hero:
    build:
      context: .
      dockerfile: docker/bot.dockerfile
    restart: always
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"
        labels: "production_status"
        env: "os"

  postgres:
    build:
      context: .
      dockerfile: docker/postgresql.dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ai-hero-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"
        labels: "production_status"
        env: "os"

volumes:
  ai-hero-postgres-data:
